### ISSUE TITLE
Environment file issue

### ISSUE THREAD

**Issue by nassimgh9** [UBC-MDS/bank-marketing-analysis#15]
Hi guys, does the environment file work for you to install the environment? I used this command conda env create -f environment.yaml but it did not work
[8:54](https://ubc-mds.slack.com/archives/C064PN37QAJ/p1700369651937909)
this is the error I get: Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed
PackagesNotFoundError: The following packages are not available from current channels:
 - pandas=pandas*
Current channels:
 - https://conda.anaconda.org/conda-forge/osx-arm64
 - https://repo.anaconda.com/pkgs/main/osx-arm64
 - https://repo.anaconda.com/pkgs/r/osx-arm64
To search for alternate channels that may provide the conda package you're
looking for, navigate to
  https://anaconda.org/
and use the search bar at the top of the page.

**Comment by nassimgha** [comment]
Fixed it
