### ISSUE TITLE
Null category in NDA but we had fixed it, maybe not the last version on GitHub

### ISSUE THREAD

**Issue by nassimgha** [UBC-MDS/bank-marketing-analysis#17]
Hi everyone!
As I was editing the file, I noticed there is still null categories in the EDA. I remember we fixed it in group meeting. So, I am not sure maybe the file on GitHub is not the last one. Could you please check?

**Comment by nassimgha** [comment]
Is it OK that we have null category in NDA, although we have used imputer in preprocessing to handle it?

**Comment by Marcony1** [comment]
Thank you Nasim, we didn't mention it here, but we fixed it in the in-person meeting afterwards.
